export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'

export const REQUEST_FAV_POKEMON = 'REQUEST_FAV_POKEMON'
export const RECEIVE_FAV_POKEMON = 'RECEIVE_FAV_POKEMON'

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

