export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'

export const REQUEST_FAV_POKEMON = 'REQUEST_FAV_POKEMON'
export const RECEIVE_FAV_POKEMON = 'RECEIVE_FAV_POKEMON'

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

export const REQUEST_TYPES = 'REQUEST_TYPES'
export const RECEIVE_TYPES = 'RECEIVE_TYPES'

export const REQUEST_CREATE_POKEMON = 'REQUEST_CREATE_POKEMON'
export const RECEIVE_CREATE_POKEMON = 'RECEIVE_CREATE_POKEMON'

